# Please refer to the example for modification

# Menu
menu:
  home: / || 首页
  archives: /archives || 归档
  tags: /tags || 标签
  categories: /categories || 分类
  about: /about || 关于

# Social
social:
  qq: tencent://message/?Menu=yes&uin=894519210 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/izhaoo || icongithub-fill || '#24292E'
  email: mailto:izhaoo@163.com || iconmail

# Color
color:
  default: "#33333D"
  link: "#FFBE5B"

# Donate
donate:
  alipay: https://pic.izhaoo.com/alipay.jpg
  wechat: https://pic.izhaoo.com/wechat.jpg

# Preview
preview:
  enable: true
  model: wave #cloud

# 相册
galleries:
  enable: true
  title: 摄影
  subtitle: Photography

# 文章封面图片
post_image: /image/post-image.jpg

# 欢迎图片
welcome_image: /image/welcome-image.jpg

# Favicon
favicon: /image/favicon.ico

# 网站关键字
keywords: zhaoo

# 版权信息
copyright: <p>Copyright© 2019-2019 | <a target="_blank" href="https://www.izhaoo.com">zhaoo</a> .AllRightsReserved</p>

# 格言
motto:
  api: # 'http://localhost:3000/api/motto'   # use the hexo-plugin-motto
  default: 我在开了灯的床头下，想问问自己的心啊。

# 插件
fancybox: true
pjax: false
highlight: true
lazyload: true

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  justifiedGallery_js: https://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/xcode.min.css
  iconfont_css: //at.alicdn.com/t/font_1445822_58xq2j9v1id.css
  justifiedGallery_css: https://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css

# Gitalk
gitalk:
  enable: false
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs:

# Custom
custom:
  head:
  foot: